// Windows — 사용자 Scheduled Task (설계 §4.3).
//
// 시스템 서비스가 아니라 **로그인한 사용자의 작업**이다. `/RU` 없이 만들면 현재 사용자로
// 등록되고, 그것이 이 계약의 경계다.
//
// 반복은 Task Scheduler 가 한다(`/SC MINUTE /MO n`). ASC 는 한 회차만 도는 명령을 준다.

import { execFile } from 'node:child_process'
import { createHash } from 'node:crypto'
import { mkdir, rm, writeFile } from 'node:fs/promises'
import { homedir } from 'node:os'
import { dirname, join } from 'node:path'
import { promisify } from 'node:util'

import {
  SERVICE_LABEL,
  type PersistentRuntimeAdapter,
  type ServiceCommand,
  type ServiceState,
} from '../../core/distribution/persistent-runtime.ts'

const run = promisify(execFile)

/** 작업 이름. `\` 없이 두면 루트 폴더에 만들어진다. */
export const TASK_NAME = SERVICE_LABEL

/**
 * `/TR` 에 들어갈 한 줄.
 *
 * schtasks 는 명령을 문자열 하나로 받는다 — 경로에 공백이 있으면 통째로 깨지므로
 * 각 조각을 따옴표로 감싼다.
 *
 * **따옴표는 `"` 하나다.** 셸을 거치지 않고 `execFile` 로 인자를 넘기므로 Windows 쪽
 * 이스케이프는 Node 가 한다. 여기서 `\"` 를 손으로 넣으면 그 위에 한 겹이 더 붙어
 * schtasks 가 백슬래시를 값으로 읽고, `C:\Program Files\...` 가 공백에서 잘린다.
 */
export function taskRunLine(command: ServiceCommand): string {
  const quote = (value: string) => `"${value}"`
  return [command.program, ...command.args].map(quote).join(' ')
}

/**
 * 창 없이 돌게 하는 한 겹 (#76).
 *
 * `node.exe` 는 콘솔 프로그램이라 Task Scheduler 가 회차마다 창을 띄운다. `<Hidden>` 은
 * 이것을 고치지 않는다 — 그 값은 작업 목록에서 감출지를 정하는 UI 플래그이고 실행 창과
 * 무관하다는 것을 실측으로 확인했다.
 *
 * 비대화형 등록(`/RU <user> /NP`)도 답이 아니었다: 일반 사용자 설치 경로에서 권한 거부와
 * 비밀번호 프롬프트가 났고, 그 방식은 자격을 저장하지 않는 대신 사용자 보호 자격에 닿지
 * 못해 외부 통로가 조용히 실패할 수 있다.
 *
 * 남는 것은 Windows 가 실제로 제공하는 한 가지다: **GUI 서브시스템 프로그램을 등록하고
 * 그것이 콘솔 프로그램을 숨긴 채 띄우게 한다.** `wscript.exe` 가 그 프로그램이고,
 * Run 의 두 번째 인자 0 이 숨김이다. 새 의존성을 들이지 않는다.
 */
export function launcherScript(command: ServiceCommand): string {
  // VBScript 문자열 안의 따옴표는 겹쳐 쓴다. 경로에 공백이 있는 것이 기본값이므로
  // (Program Files) 이 이스케이프가 곧 동작 조건이다.
  const inner = [command.program, ...command.args]
    .map((value) => DQ + DQ + value.split(DQ).join(DQ + DQ) + DQ + DQ)
    .join(' ')
  return [
    "' Generated by ASC. Do not edit - `asc setup` rewrites this file.",
    "'",
    "' wscript.exe is a GUI-subsystem host, so Windows creates no console for it,",
    "' and Run's second argument (0) starts the child hidden. That pair is what",
    "' keeps a scheduled run off the person's screen.",
    'Set shell = CreateObject(' + DQ + 'WScript.Shell' + DQ + ')',
    'shell.Run ' + DQ + inner + DQ + ', 0, False',
    '',
  ].join(CRLF)
}

const DQ = String.fromCharCode(34)
const CRLF = String.fromCharCode(13, 10)

/** 등록물이 가리킬 wscript 한 줄. 명령 지문을 인자로 실어 drift 가 그대로 드러나게 한다. */
export function taskLauncherLine(scriptPath: string, command: ServiceCommand): string {
  const quote = (value: string) => DQ + value + DQ
  return ['wscript.exe', '//B', '//Nologo', scriptPath, commandFingerprint(command)].map(quote).join(' ')
}

/**
 * 등록된 한 줄만 보고도 안쪽 명령이 달라진 것을 알 수 있게 하는 값.
 *
 * wscript 를 거치면 실제 명령이 등록물에서 사라진다 — 그러면 진입점이나 간격이 바뀌어도
 * 등록은 그대로 보이고 STALE 판정이 서지 않는다. 지문을 인자로 실어 그 눈을 되살린다.
 */
export function commandFingerprint(command: ServiceCommand): string {
  return createHash('sha256').update(taskRunLine(command)).digest('hex').slice(0, 16)
}

/** wscript 스크립트가 사는 자리. 등록물의 로그와 같은 곳 — 둘 다 이 adapter 의 산출물이다. */
export function launcherPath(command: ServiceCommand): string {
  return join(command.logPath ? dirname(command.logPath) : homedir(), 'service-launcher.vbs')
}

/** 분 단위 반복. 1분 아래로는 Task Scheduler 가 받지 않는다. */
export const taskMinutes = (intervalSeconds: number): number => Math.max(1, Math.round(intervalSeconds / 60))

/**
 * schtasks 출력 해독.
 *
 * `/XML` 은 UTF-16LE 로 나온다. 필드 이름이 로케일에 따라 번역되는 `/FO LIST /V` 대신
 * 이것을 쓰는 이유가 그거다 — 태그 이름은 어느 언어에서나 같다.
 */
const decodeSchtasksOutput = (raw: Buffer): string =>
  raw.length >= 2 && raw[0] === 0xff && raw[1] === 0xfe ? raw.toString('utf16le') : raw.toString('utf8')

const XML_ENTITIES: Record<string, string> = { '&amp;': '&', '&lt;': '<', '&gt;': '>', '&quot;': '"', '&apos;': "'" }

/**
 * ISO-8601 기간을 분으로. 모르는 형태면 `null`.
 *
 * **문자열로 비교하면 안 된다** — Task Scheduler 는 받은 값을 자기 방식으로 정규화한다.
 * `/MO 60` 으로 등록한 것이 `PT1H` 로 저장되므로 `PT60M` 을 기대하면 같은 등록을
 * 낡았다고 읽는다 (실기계 실측).
 */
export function durationMinutes(value: string): number | null {
  const parsed = /^P(?:(\d+)D)?T(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?$/.exec(value.trim())
  if (!parsed) return null
  const [, days, hours, minutes, seconds] = parsed
  return Number(days ?? 0) * 1440 + Number(hours ?? 0) * 60 + Number(minutes ?? 0) + Number(seconds ?? 0) / 60
}

/**
 * 등록물이 지금 형태와 어긋난 점. 없으면 `null`.
 *
 * 명령만 보던 때에는 **간격이 달라도 CURRENT 로 읽혔다** — `intervalSeconds` 는
 * `taskRunLine` 에 들어가지 않기 때문이다. launchd·systemd 는 간격이 unit 내용에
 * 있어 그냥 잡히는데 여기만 눈이 없었다.
 */
export function registrationDrift(xml: string, command: ServiceCommand): string | null {
  const text = xml.replace(/&(?:amp|lt|gt|quot|apos);/g, (entity) => XML_ENTITIES[entity] ?? entity)
  // Command 와 Arguments 는 태그로 갈려 있다. 태그를 지우면 등록한 그 한 줄로 돌아온다.
  const flattened = text.replace(/<\/?[^>]+>/g, ' ').replace(/\s+/g, ' ')
  // 등록물은 실행기를 부르고 실행기가 명령을 부른다 (#76). 그래서 등록된 한 줄에 명령
  // 자체는 없고 **지문**이 있다 — 진입점이나 간격이 바뀌면 지문이 바뀌고 여기서 잡힌다.
  // 실행기를 거치지 않던 옛 등록도 STALE 로 읽혀 다음 수렴에서 바뀐다.
  if (!flattened.includes(commandFingerprint(command))) return `${TASK_NAME} runs a different command`
  if (!/wscript/i.test(flattened)) return `${TASK_NAME} still runs a console program directly`

  const interval = /<Interval>([^<]+)<\/Interval>/.exec(text)?.[1]?.trim()
  const wanted = taskMinutes(command.intervalSeconds)
  if (interval === undefined || durationMinutes(interval) !== wanted) {
    return `${TASK_NAME} repeats every ${interval ?? 'an unknown interval'}, not every ${wanted} min`
  }

  return null
}

export type SchtasksDeps = {
  exec?: (command: string, args: readonly string[]) => Promise<string>
}

export function schtasksAdapter(deps: SchtasksDeps = {}): PersistentRuntimeAdapter {
  const exec =
    deps.exec ??
    (async (command: string, args: readonly string[]) => {
      // windowsHide 는 여기서 직접 준다 — runExternal 은 문자열을 돌려주는데 `/XML` 은
      // UTF-16 이라 버퍼로 받아야 한다. 창을 숨기는 이유는 runExternal 과 같다.
      const { stdout } = await run(command, [...args], { windowsHide: true, encoding: 'buffer' })
      return decodeSchtasksOutput(stdout as unknown as Buffer)
    })

  return {
    id: 'schtasks',
    async supported() {
      return process.platform === 'win32'
    },
    async status(command) {
      const query = await exec('schtasks', ['/Query', '/TN', TASK_NAME, '/XML', 'ONE']).catch(() => null)
      // 조회가 실패하는 것은 대개 "없다"이다. 없는 것과 못 읽은 것을 구분할 방법이
      // schtasks 에는 없으므로, 없는 쪽으로 읽고 install 이 다시 판정하게 둔다.
      if (query === null) return { kind: 'ABSENT' } satisfies ServiceState
      const drift = registrationDrift(query, command)
      return drift === null
        ? ({ kind: 'CURRENT', detail: TASK_NAME } satisfies ServiceState)
        : ({ kind: 'STALE', detail: drift } satisfies ServiceState)
    },
    async install(command) {
      // `/F` 로 덮어쓴다 — 같은 이름의 우리 등록을 지금 형태로 수렴시키는 것이다.
      //
      // 등록물은 여전히 `InteractiveToken` 이다(일반 사용자 경로에서 그것이 유일하게
      // 되는 것이다). 달라진 것은 등록물이 콘솔 프로그램을 직접 부르지 않는다는 것뿐이다:
      // GUI 서브시스템 호스트를 부르고, 그것이 회차를 숨긴 채 띄운다 (#76).
      const script = launcherPath(command)
      await mkdir(dirname(script), { recursive: true })
      await writeFile(script, launcherScript(command), 'utf8')
      await exec('schtasks', [
        '/Create',
        '/F',
        '/TN',
        TASK_NAME,
        '/TR',
        taskLauncherLine(script, command),
        '/SC',
        'MINUTE',
        '/MO',
        String(taskMinutes(command.intervalSeconds)),
      ])
    },
    async uninstall(command) {
      await exec('schtasks', ['/Delete', '/TN', TASK_NAME, '/F']).catch(() => undefined)
      // 등록을 지우면 그 등록만 부르던 실행기도 남을 이유가 없다.
      if (command) await rm(launcherPath(command), { force: true }).catch(() => undefined)
    },
  }
}
